name: Run tests and build application

permissions:
  id-token: write
  contents: read
  attestations: write

on:
  push:
    branches: [main, "ci/artifact-attestation"]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: make test

  build:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build (unsigned)
        run: make build-unsigned

      - name: Package application bundle
        run: ditto -c -k --keepParent build/DerivedData/Build/Products/Release/palium.app palium.app.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: palium
          path: palium.app.zip

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: palium.app.zip
